### PR TITLE
fix: change the author in retest for konflux updates prs in v0.1

### PR DESCRIPTION
**Pull request by jinqi7**

### CODE REVIEW

**Review by flacatus — APPROVED** [review]

**Comment by psturc** [comment]
@jinqi7 we have this change already in v0.2 - why was it changed in v0.1?

**Comment by jinqi7** [comment]
> @jinqi7 we have this change already in v0.2 - why was it changed in v0.1?

Because I want to use `tasks.test-metadata.results.pull-request-author`. In v0.2, we only have `job-spec` in results of the task.

**Comment by jinqi7** [comment]
> @jinqi7 ah, I see, you'd have to [parse the `job-spec` in your task](https://github.com/konflux-ci/tekton-integration-catalog/pull/67/files#diff-98ff55df9fc3a972deeff03faeaddd5794f593ed3c4a22db8e707226ad950d1fR53) in order to get the required metadata value

I need to use it in the `when` clause where I can't parse `job-spec`. So, I used v0.1 instead of v0.2.

**Pull request merged**
